#!/bin/bash
#
# Run the monitoring of the PP nodes
#
# Depends on ARCHER_MON_BASEDIR being set
#
ssh mom1 "$ARCHER_MON_BASEDIR/monitoring/mom-nodes/cpu_and_mem_use.bash"
ssh mom2 "$ARCHER_MON_BASEDIR/monitoring/mom-nodes/cpu_and_mem_use.bash"
ssh mom3 "$ARCHER_MON_BASEDIR/monitoring/mom-nodes/cpu_and_mem_use.bash"
ssh mom4 "$ARCHER_MON_BASEDIR/monitoring/mom-nodes/cpu_and_mem_use.bash"
ssh mom5 "$ARCHER_MON_BASEDIR/monitoring/mom-nodes/cpu_and_mem_use.bash"
