#!/bin/bash
#
# Run the monitoring of applications
#
# Depends on ARCHER_MON_BASEDIR being set
#
$ARCHER_MON_BASEDIR/monitoring/applications/running_applications.bash >> $ARCHER_MON_LOGDIR/running_applications.log
