#!/bin/bash
#
# Plot usage data
#
# Depends on ARCHER_MON_BASEDIR being set
#
# As we now plot multiple job sizes we need to use different versions until the
# data catches up
re='1y'
if [[ $1 =~ $re ]]; then
   python $ARCHER_MON_BASEDIR/reporting/usage/plot_usage_single.py $1 usage
else
   python $ARCHER_MON_BASEDIR/reporting/usage/plot_usage.py $1 usage
fi
python $ARCHER_MON_BASEDIR/reporting/usage/plot_queues.py $1 queues
