#!/bin/bash
#
# Get total usage stats
#
# Depends on ARCHER_MON_BASEDIR being set
#
$ARCHER_MON_BASEDIR/monitoring/usage/get_usage.bash
$ARCHER_MON_BASEDIR/monitoring/usage/get_queues.bash
$ARCHER_MON_BASEDIR/monitoring/usage/get_low.bash
